### PR TITLE
Remove Hub hypermedia project

### PR DESCRIPTION
**Pull request by bkeepers**
@pengwynn is already working with a group of students on this problem. We should probably not encourage GSoC participants to work on this.

/cc @mislav

### CODE REVIEW

**Comment by pengwynn** [comment]
Thanks, @bkeepers. :+1:

**Comment by shanzi** [comment]
@bkeepers Hi, will this prevents new ideas on `Hub`? 

GSoC seems has a cap for total number of  accepted students of a organization based on the number of target projects applied. If one of `Hub`'s idea has already be settled down with candidates, a slot has been filled.

But I think It seems the hypermedia project is more a `go-octokit` project than a `Hub` project. So will this affect the other idea (shell auto completion one)?

**Comment by bkeepers** [comment]
@shanzi nope. Feel free to explore other ideas on hub. We do have a limited number of students we can accept, but it doesn't matter which projects they will be on.

**Comment by mislav** [comment]
Should I come up with some alternatives to this, so that hub is listed with more project ideas than just one?

**Pull request merged**
